### ISSUE TITLE
lstm_crf, y label onehot?

### ISSUE THREAD

**Issue by mujizi** [BrambleXu/nlp-beginner-guide-keras#7]
hello，
Your lstm +crf model y label use onehot, I do n’t think it needs one hot. I do n’t know if it ’s wrong. I think crf is calculating a sequence loss.

**Comment by BrambleXu** [comment]
The [y label](https://github.com/BrambleXu/nlp-beginner-guide-keras/blob/master/bilstm-crf/data/ner_dataset.csv) of bilstm-crf uses the [IOB2](https://datascience.stackexchange.com/questions/37824/difference-between-iob-and-iob2-format) format, not the one-hot format.
